#!/bin/bash
if !(git svn --version 2>&1 | grep 'git-svn' > /dev/null); then
  echo "git-svn doesn't seem to be installed.";
  exit 1
fi
if !(git remote | grep 'upstream' > /dev/null); then
  git remote add upstream git://git.webkit.org/WebKit.git;
  git fetch upstream;
  cat << EOF >> .git/config
[svn-remote "svn"]
  url = http://svn.webkit.org/repository/webkit
  fetch = trunk:refs/remotes/upstream/master
  branches = releases/WebKitGTK/webkit-2*:refs/heads/webkitgtk/*
  branches = branches/safari-60*-branch:refs/heads/safari/*
EOF
fi
# Running this for the first time will take hours!
git svn fetch
# Push the webkitgtk, safari and trunk branches
git push origin refs/heads/webkitgtk/*:refs/heads/webkitgtk/* refs/heads/safari/*:refs/heads/safari/* upstream/master:master
